### Add GcBasic
POST http://localhost:8080/gc-basic/2
Content-Type: application/json

{"guid" :  "guid:10", "level" : 122 }

### Add ChallengeEvents
POST http://localhost:8080/challenge-events/2
Content-Type: application/json

{"guid" :  "guid:10", "time" : 55 }